baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jose Luis Pabon Website"

theme = "academia-hugo"
# email = "test@example.com"
email_form = 0

## To get dark as the default add "dark" as a class to body. 
## Still haven't found the configuration place for this. 